[package]
name = "merge-mania-server"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.5"
warp = "0.3"
