[game]
# Milliseconds per tick
tick_millis = 1000

# Reset game state when starting server
reset = false

[[teams]]
id = 1
name = "Team 1"
password = "team1"

[[teams]]
id = 2
name = "Team 2"
password = "team2"

[[teams]]
id = 3
name = "Team 3"
password = "team3"

[[teams]]
id = 4
name = "Team 4"
password = "team4"

[[teams]]
id = 5
name = "Team 5"
password = "team5"

[[teams]]
id = 6
name = "Team 6"
password = "team6"

[[teams]]
id = 7
name = "Team 7"
password = "team7"

[[products.tiers]]
id = 1
name = "Fruit"
products = [
    { name = "Apple", cost = 1, sprite_path = "red-apple.png" },
    { name = "Banana", cost = 3, sprite_path = "banana.png" },
    { name = "Pineapple", cost = 8, sprite_path = "pineapple.png" },
    { name = "Cherries", cost = 19, sprite_path = "cherries.png" },
    { name = "Strawberry", cost = 43, sprite_path = "strawberry.png" },
    { name = "Watermelon", cost = 94, sprite_path = "watermelon.png" },
    { name = "Grape", cost = 201, sprite_path = "grapes.png" },
    { name = "Lemon", cost = 423, sprite_path = "lemon.png" },
    { name = "Tangerine", cost = 880, sprite_path = "tangerine.png" },
    { name = "Pear", cost = 1815, sprite_path = "pear.png" },
    { name = "Peach", cost = 3719, sprite_path = "peach.png" },
    { name = "Mango", cost = 7582, sprite_path = "mango.png" },
    { name = "Blueberries", cost = 15397, sprite_path = "blueberries.png" },
]

[[products.tiers]]
id = 2
name = "Vegetable"
products = [
    { name = "Tomato", cost = 15, sprite_path = "tomato.png" },
    { name = "Cucumber", cost = 31, sprite_path = "cucumber.png" },
    { name = "Onion", cost = 64, sprite_path = "onion.png" },
    { name = "Carrot", cost = 131, sprite_path = "carrot.png" },
    { name = "Eggplant", cost = 267, sprite_path = "eggplant.png" },
    { name = "Bell Pepper", cost = 542, sprite_path = "bell-pepper.png" },
    { name = "Potato", cost = 1097, sprite_path = "potato.png" },
    { name = "Corn", cost = 2215, sprite_path = "ear-of-corn.png" },
    { name = "Broccoli", cost = 4464, sprite_path = "broccoli.png" },
    { name = "Garlic", cost = 8983, sprite_path = "garlic.png" },
    { name = "Mushroom", cost = 18055, sprite_path = "mushroom.png" },
]

[[products.tiers]]
id = 3
name = "Bread"
products = [
    { name = "Bread", cost = 225, sprite_path = "bread.png" },
    { name = "Croissant", cost = 451, sprite_path = "croissant.png" },
    { name = "Baguette", cost = 904, sprite_path = "baguette-bread.png" },
    { name = "Flatbread", cost = 1809, sprite_path = "flatbread.png" },
    { name = "Pretzel", cost = 3621, sprite_path = "pretzel.png" },
    { name = "Bagel", cost = 7247, sprite_path = "bagel.png" },
    { name = "Pancake", cost = 14502, sprite_path = "pancakes.png" },
    { name = "Waffle", cost = 29017, sprite_path = "waffle.png" },
    { name = "Fortune Cookie", cost = 58055, sprite_path = "fortune-cookie.png" },
]

[[products.tiers]]
id = 4
name = "Birds"
products = [
    { name = "Egg", cost = 3375, sprite_path = "egg.png" },
    { name = "Baby Chick", cost = 6751, sprite_path = "baby-chick.png" },
    { name = "Duck", cost = 13504, sprite_path = "duck.png" },
    { name = "Swan", cost = 27011, sprite_path = "swan.png" },
    { name = "Owl", cost = 54027, sprite_path = "owl.png" },
    { name = "Peacock", cost = 108062, sprite_path = "peacock.png" },
    { name = "Eagle", cost = 216137, sprite_path = "eagle.png" },
]

[[factories.tiers]]
id = 101
name = "Fruit factory"
levels = [
    { name = "Fruit fac lvl 1", cost_buy = [5], cost_sell = [3], time = 60, drops = [
        { item = "1.0", chance = 0.95 },
        { item = "1.1", chance = 0.04 },
        { item = "2.0", chance = 0.01 },
    ], sprite_path = "deciduous-tree.png" },
    { name = "Fruit fac lvl 2", cost_sell = [6], time = 54, drops = [
        { item = "1.0", chance = 0.90 },
        { item = "1.1", chance = 0.06 },
        { item = "1.2", chance = 0.01 },
        { item = "2.0", chance = 0.03 },
    ], sprite_path = "deciduous-tree.png" },
    { name = "Fruit fac lvl 3", cost_sell = [12], time = 48, drops = [
        { item = "1.0", chance = 0.77 },
        { item = "1.1", chance = 0.16 },
        { item = "1.2", chance = 0.02 },
        { item = "2.0", chance = 0.05 },
    ], sprite_path = "deciduous-tree.png" },
    { name = "Fruit fac lvl 4", cost_sell = [24], time = 42, drops = [
        { item = "1.0", chance = 0.62 },
        { item = "1.1", chance = 0.28 },
        { item = "1.2", chance = 0.03 },
        { item = "2.0", chance = 0.07 },
    ], sprite_path = "deciduous-tree.png" },
    { name = "Fruit fac lvl 5", cost_sell = [48], time = 36, drops = [
        { item = "1.0", chance = 0.33 },
        { item = "1.1", chance = 0.50 },
        { item = "1.2", chance = 0.05 },
        { item = "1.3", chance = 0.01 },
        { item = "2.0", chance = 0.10 },
    ], sprite_path = "deciduous-tree.png" },
    { name = "Fruit fac lvl 6", cost_sell = [96], time = 30, drops = [
        { item = "1.1", chance = 0.72 },
        { item = "1.2", chance = 0.08 },
        { item = "1.3", chance = 0.03 },
        { item = "2.0", chance = 0.16 },
        { item = "2.1", chance = 0.01 },
    ], sprite_path = "deciduous-tree.png" },
    { name = "Fruit fac lvl 7", cost_sell = [192], time = 24, drops = [
        { item = "1.1", chance = 0.59 },
        { item = "1.2", chance = 0.13 },
        { item = "1.3", chance = 0.05 },
        { item = "2.0", chance = 0.20 },
        { item = "2.1", chance = 0.03 },
    ], sprite_path = "deciduous-tree.png" },
]

[[factories.tiers]]
id = 102
name = "Bread factory"
levels = [
    { name = "Bread fac lvl 1", cost_buy = [["2.4", 1]], cost_sell = [79], time = 60, drops = [
        { item = "3.0", chance = 0.95 },
        { item = "3.1", chance = 0.04 },
        { item = "4.0", chance = 0.01 },
    ], sprite_path = "chicken.png" },
    { name = "Bread fac lvl 2", cost_sell = [158], time = 51, drops = [
        { item = "3.0", chance = 0.87 },
        { item = "3.1", chance = 0.09 },
        { item = "3.2", chance = 0.01 },
        { item = "4.0", chance = 0.03 },
    ], sprite_path = "chicken.png" },
    { name = "Bread fac lvl 3", cost_sell = [316], time = 42, drops = [
        { item = "3.0", chance = 0.54 },
        { item = "3.1", chance = 0.32 },
        { item = "3.2", chance = 0.05 },
        { item = "3.3", chance = 0.01 },
        { item = "4.0", chance = 0.07 },
        { item = "4.1", chance = 0.01 },
    ], sprite_path = "chicken.png" },
    { name = "Bread fac lvl 4", cost_sell = [732], time = 33, drops = [
        { item = "3.0", chance = 0.28 },
        { item = "3.1", chance = 0.50 },
        { item = "3.2", chance = 0.07 },
        { item = "3.3", chance = 0.03 },
        { item = "4.0", chance = 0.10 },
        { item = "4.1", chance = 0.02 },
    ], sprite_path = "chicken.png" },
    { name = "Bread fac lvl 5", cost_sell = [1464], time = 24, drops = [
        { item = "3.1", chance = 0.42 },
        { item = "3.2", chance = 0.18 },
        { item = "3.3", chance = 0.13 },
        { item = "4.0", chance = 0.22 },
        { item = "4.1", chance = 0.05 },
    ], sprite_path = "chicken.png" },
]

[defaults]
money = 10
energy = 5
inventory = [
    "1.0",
    "1.0",
    "1.0",
    "101.0",
]
